
import os

from .ugraph import UGraph


class UniqueCertificates:
    """
    Parse the unique certificates file generated by the cpp and provides a generator of graphs of type UGraph
    """

    def __init__(self, fi_certificates: str = None):
        if fi_certificates is None:
            fi_certificates = '../../../data/db_unique_certificates.csv'
        if not os.path.isfile(fi_certificates):
            raise Exception("File not found: {}".format(fi_certificates))

        self.file = open(fi_certificates, 'r')

    def __iter__(self):
        try:
            for line in self.file:
                num_vertices, graph_id = line.split(",")
                num_vertices = int(num_vertices)
                graph_id = int(graph_id)
                yield UGraph.graph_from_graph_id(num_vertices, graph_id)
        except ValueError as ve:
            print(line)
            raise ve
        finally:
            self.file.close()
